[package]
authors.workspace = true
description.workspace = true
edition.workspace = true
name = "watch_downloads"
readme = "README.md"
version.workspace = true

[lib]
name = "watch_downloads"
path = "src/lib.rs"

[[bin]]
name = "watch_downloads"
path = "src/main.rs"

[dependencies]
clipboard-rs = "0.3.5"
dirs = "7.0.0"
thiserror = "2.0.20"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
