#!/bin/bash

# Function to prompt user for input
prompt() {
    local message=$1
    local default=$2
    read -e -p "$message [$default]: " input # Added -e for readline completion
    echo "${input:-$default}"
}

# Interactive prompts for plist configuration
label=$(prompt "Enter the Label for the LaunchAgent" "com.example.myagent")
program_args_input=$(IFS=' ' prompt "Enter the Program command to execute" "/absolute/path/to/your/program args...")
start_interval=$(prompt "Enter the StartInterval in seconds (leave empty for none)" "")
run_at_load=$(prompt "Should it run at load? (true/false)" "true")
keep_alive=$(prompt "Should it keep alive? (true/false)" "true")
standard_out_path=$(prompt "Enter the StandardOutPath" "/dev/null")
standard_err_path=$(prompt "Enter the StandardErrorPath" "/dev/null")
save_to_file=$(prompt "Where to save the plist file? (without filename)" "~/Library/LaunchAgents/")
save_to_file="${save_to_file%/}/${label}.plist"

cat >$save_to_file <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
EOF

if [ ! -f "$save_to_file" ]; then
    echo "Error: $save_to_file no such file, maybe due to permission denied."
    exit 1
fi

# Generate the plist file content
cat >>$save_to_file <<EOF
<dict>
    <key>Label</key>
    <string>$label</string>
    <key>ProgramArguments</key>
    <array>
EOF

# Loop through the arguments and add them to the array
if [ -n "$program_args_input" ]; then
    IFS=' ' read -r -a args <<< "$program_args_input"
    for arg in "${args[@]}"; do
    cat >>$save_to_file <<EOF
        <string>$arg</string>
EOF
    done
fi

cat >>$save_to_file <<EOF
    </array>
EOF

if [[ -n "$start_interval" ]]; then
    cat >>$save_to_file <<EOF
    <key>StartInterval</key>
    <integer>$start_interval</integer>
EOF
fi

cat >>$save_to_file <<EOF
    <key>RunAtLoad</key>
    <$run_at_load/>
    <key>KeepAlive</key>
    <$keep_alive/>
    <key>StandardOutPath</key>
    <string>$standard_out_path</string>
    <key>StandardErrorPath</key>
    <string>$standard_err_path</string>

   <!-- 设置环境变量 -->
   <key>EnvironmentVariables</key>
   <dict>
      <key>PATH</key>
      <string>/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
   </dict>
</dict>
</plist>
EOF
echo "Output Result (saved to $save_to_file):"

echo
cat $save_to_file
echo

# Check if StandardOutPath and StandardErrorPath are writable
if [ ! -w "$standard_out_path" ]; then
    echo "Warning: StandardOutPath ($standard_out_path) is not writable."
fi

if [ ! -w "$standard_err_path" ]; then
    echo "Warning: StandardErrorPath ($standard_err_path) is not writable."
fi