[package]
name = "appgen"
version.workspace = true
edition.workspace = true
description.workspace = true
readme = "README.md"
authors.workspace = true

[dependencies]
clap = { version = "4.6", features = ["derive"] }
anyhow = "1.0"
plist = "1.10"
fs_extra = "1.3"
chrono = "0.4.45"

[[bin]]
name = "appgen"
path = "src/main.rs"

[[example]]
name = "log_example"
path = "src/log_example.rs"
